install casks to ~/Applications

diff --git a/bin/brew b/bin/brew
--- a/bin/brew
+++ b/bin/brew
@@ -1,13 +1,15 @@
 #!/bin/bash -p
 set -u
 
+export HOMEBREW_CASK_OPTS="--appdir=~/Applications ${HOMEBREW_CASK_OPTS}"
+
 # Fail fast with concise message when not using bash
 # Single brackets is needed here for POSIX compatibility
 # shellcheck disable=SC2292
 if [ -z "${BASH_VERSION:-}" ]
 then
-  echo "Error: Bash is required to run brew." >&2
-  exit 1
+    echo "Error: Bash is required to run brew." >&2
+    exit 1
 fi
 
 set +o posix # as we are using bash now
@@ -15,68 +17,68 @@ set +o posix # as we are using bash now
 # Fail fast with concise messages when PWD has issues
 if [[ -z "${PWD-}" ]]
 then
-  echo "Error: \$PWD must be set to run brew." >&2
-  exit 1
+    echo "Error: \$PWD must be set to run brew." >&2
+    exit 1
 fi
 if ! [[ -d "${PWD}" ]]
 then
-  echo "Error: The current working directory must exist to run brew." >&2
-  exit 1
+    echo "Error: The current working directory must exist to run brew." >&2
+    exit 1
 fi
 if ! [[ -r "${PWD}" ]]
 then
-  echo "Error: The current working directory must be readable to ${USER} to run brew." >&2
-  exit 1
+    echo "Error: The current working directory must be readable to ${USER} to run brew." >&2
+    exit 1
 fi
 
 # Fail fast with concise message when HOME is unset
 if [[ -z "${HOME:-}" ]]
 then
-  echo "Error: \$HOME must be set to run brew." >&2
-  exit 1
+    echo "Error: \$HOME must be set to run brew." >&2
+    exit 1
 fi
 
 quiet_cd() {
-  CDPATH='' cd -- "$@" &>/dev/null || return
+    CDPATH='' cd -- "$@" &>/dev/null || return
 }
 
 symlink_target_directory() {
-  local target target_dirname
-  target="$(readlink "$1")"
-  target_dirname="$(dirname "${target}")"
-  local directory="$2"
-  quiet_cd "${directory}" && quiet_cd "${target_dirname}" && pwd -P
+    local target target_dirname
+    target="$(readlink "$1")"
+    target_dirname="$(dirname "${target}")"
+    local directory="$2"
+    quiet_cd "${directory}" && quiet_cd "${target_dirname}" && pwd -P
 }
 
 # Enable and use default Bash builtins rather than user-defined functions
 builtin enable compgen unset
 for cmd in $(builtin compgen -A builtin)
 do
-  builtin unset -f "${cmd}"
-  builtin enable "${cmd}"
+    builtin unset -f "${cmd}"
+    builtin enable "${cmd}"
 done
 unset cmd
 
 # Avoid picking up any random `sudo` in `PATH`.
 if [[ -x /usr/bin/sudo ]]
 then
-  SUDO=/usr/bin/sudo
+    SUDO=/usr/bin/sudo
 else
-  # Do this after ensuring we're using default Bash builtins.
-  SUDO="$(command -v sudo 2>/dev/null)"
+    # Do this after ensuring we're using default Bash builtins.
+    SUDO="$(command -v sudo 2>/dev/null)"
 fi
 
 # Reset sudo timestamp to avoid running unauthorized sudo commands
 if [[ -n "${SUDO}" ]]
 then
-  "${SUDO}" --reset-timestamp 2>/dev/null || true
+    "${SUDO}" --reset-timestamp 2>/dev/null || true
 fi
 unset SUDO
 
 # Take the HOMEBREW_PATH if we are running brew within brew, otherwise we would lose the original path.
 if [[ -n "${HOMEBREW_BREW_FILE:-}" && -n "${HOMEBREW_PATH:-}" ]]
 then
-  PATH="${HOMEBREW_PATH}"
+    PATH="${HOMEBREW_PATH}"
 fi
 
 BREW_FILE_DIRECTORY="$(quiet_cd "${0%/*}/" && pwd -P)"
@@ -86,7 +88,7 @@ HOMEBREW_PREFIX="${HOMEBREW_BREW_FILE%/*/*}"
 # Default to / prefix if unset or the bin/brew file.
 if [[ -z "${HOMEBREW_PREFIX}" || "${HOMEBREW_PREFIX}" = "${HOMEBREW_BREW_FILE}" ]]
 then
-  HOMEBREW_PREFIX="/"
+    HOMEBREW_PREFIX="/"
 fi
 
 HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
@@ -94,20 +96,20 @@ HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}"
 # Resolve the bin/brew symlink to find Homebrew's repository
 if [[ -L "${HOMEBREW_BREW_FILE}" ]]
 then
-  BREW_FILE_DIRECTORY="$(symlink_target_directory "${HOMEBREW_BREW_FILE}" "${BREW_FILE_DIRECTORY}")"
-  HOMEBREW_REPOSITORY="${BREW_FILE_DIRECTORY%/*}"
+    BREW_FILE_DIRECTORY="$(symlink_target_directory "${HOMEBREW_BREW_FILE}" "${BREW_FILE_DIRECTORY}")"
+    HOMEBREW_REPOSITORY="${BREW_FILE_DIRECTORY%/*}"
 fi
 
 # Try to find a /usr/local HOMEBREW_PREFIX where possible (for macOS x86_64 bottles)
 if [[ -L "/usr/local/bin/brew" && ! -L "${HOMEBREW_PREFIX}/Cellar" ]]
 then
-  USR_LOCAL_BREW_FILE_DIRECTORY="$(symlink_target_directory "/usr/local/bin/brew" "/usr/local/bin")"
-  USR_LOCAL_HOMEBREW_REPOSITORY="${USR_LOCAL_BREW_FILE_DIRECTORY%/*}"
-  if [[ "${HOMEBREW_REPOSITORY}" = "${USR_LOCAL_HOMEBREW_REPOSITORY}" ]]
-  then
-    HOMEBREW_PREFIX="/usr/local"
-  fi
-  unset USR_LOCAL_BREW_FILE_DIRECTORY USR_LOCAL_HOMEBREW_REPOSITORY
+    USR_LOCAL_BREW_FILE_DIRECTORY="$(symlink_target_directory "/usr/local/bin/brew" "/usr/local/bin")"
+    USR_LOCAL_HOMEBREW_REPOSITORY="${USR_LOCAL_BREW_FILE_DIRECTORY%/*}"
+    if [[ "${HOMEBREW_REPOSITORY}" = "${USR_LOCAL_HOMEBREW_REPOSITORY}" ]]
+    then
+        HOMEBREW_PREFIX="/usr/local"
+    fi
+    unset USR_LOCAL_BREW_FILE_DIRECTORY USR_LOCAL_HOMEBREW_REPOSITORY
 fi
 
 unset BREW_FILE_DIRECTORY
@@ -118,25 +120,25 @@ HOMEBREW_LIBRARY="${HOMEBREW_REPOSITORY}/Library"
 
 # Load Homebrew's variable configuration files from disk.
 export_homebrew_env_file() {
-  local env_file
-
-  env_file="${1}"
-  [[ -r "${env_file}" ]] || return 0
-  while read -r line
-  do
-    # only load HOMEBREW_* lines
-    [[ "${line}" = "HOMEBREW_"* ]] || continue
-    export "${line?}"
-  done <"${env_file}"
+    local env_file
+    
+    env_file="${1}"
+    [[ -r "${env_file}" ]] || return 0
+    while read -r line
+    do
+        # only load HOMEBREW_* lines
+        [[ "${line}" = "HOMEBREW_"* ]] || continue
+        export "${line?}"
+    done <"${env_file}"
 }
 
 # First, load the system-wide configuration.
 unset SYSTEM_ENV_TAKES_PRIORITY
 if [[ -n "${HOMEBREW_SYSTEM_ENV_TAKES_PRIORITY-}" ]]
 then
-  SYSTEM_ENV_TAKES_PRIORITY="1"
+    SYSTEM_ENV_TAKES_PRIORITY="1"
 else
-  export_homebrew_env_file "/etc/homebrew/brew.env"
+    export_homebrew_env_file "/etc/homebrew/brew.env"
 fi
 
 # Next, load the prefix configuration
@@ -145,9 +147,9 @@ export_homebrew_env_file "${HOMEBREW_PREFIX}/etc/homebrew/brew.env"
 # Finally, load the user configuration
 if [[ -n "${XDG_CONFIG_HOME-}" ]]
 then
-  HOMEBREW_USER_CONFIG_HOME="${XDG_CONFIG_HOME}/homebrew"
+    HOMEBREW_USER_CONFIG_HOME="${XDG_CONFIG_HOME}/homebrew"
 else
-  HOMEBREW_USER_CONFIG_HOME="${HOME}/.homebrew"
+    HOMEBREW_USER_CONFIG_HOME="${HOME}/.homebrew"
 fi
 
 export_homebrew_env_file "${HOMEBREW_USER_CONFIG_HOME}/brew.env"
@@ -155,7 +157,7 @@ export_homebrew_env_file "${HOMEBREW_USER_CONFIG_HOME}/brew.env"
 # If the system configuration takes priority, load it last.
 if [[ -n "${SYSTEM_ENV_TAKES_PRIORITY-}" ]]
 then
-  export_homebrew_env_file "/etc/homebrew/brew.env"
+    export_homebrew_env_file "/etc/homebrew/brew.env"
 fi
 
 # Copy and export all HOMEBREW_* variables previously mentioned in
@@ -163,51 +165,51 @@ fi
 
 # These variables are allowed to be set by the user as, e.g., `HOMEBREW_BROWSER`.
 MANPAGE_VARS=(
-  BAT_CONFIG_PATH
-  BAT_THEME
-  BROWSER
-  BUNDLE_USER_CACHE
-  DISPLAY
-  EDITOR
-  NO_COLOR
+    BAT_CONFIG_PATH
+    BAT_THEME
+    BROWSER
+    BUNDLE_USER_CACHE
+    DISPLAY
+    EDITOR
+    NO_COLOR
 )
 for VAR in "${MANPAGE_VARS[@]}"
 do
-  # Skip if variable value is empty.
-  [[ -z "${!VAR:-}" ]] && continue
-
-  VAR_NEW="HOMEBREW_${VAR}"
-  # Skip if existing HOMEBREW_* variable is set.
-  [[ -n "${!VAR_NEW:-}" ]] && continue
-  export "${VAR_NEW}"="${!VAR}"
+    # Skip if variable value is empty.
+    [[ -z "${!VAR:-}" ]] && continue
+    
+    VAR_NEW="HOMEBREW_${VAR}"
+    # Skip if existing HOMEBREW_* variable is set.
+    [[ -n "${!VAR_NEW:-}" ]] && continue
+    export "${VAR_NEW}"="${!VAR}"
 done
 
 # We don't want to take the user's value for, e.g., `HOMEBREW_PATH` here!
 USED_BY_HOMEBREW_VARS=(
-  CODESPACES
-  COLORTERM
-  DBUS_SESSION_BUS_ADDRESS
-  NODENV_ROOT
-  PATH
-  PYENV_ROOT
-  RBENV_ROOT
-  SSH_TTY
-  SUDO_USER
-  TMPDIR
-  TMUX
-  XDG_CACHE_HOME
-  XDG_DATA_DIRS
-  XDG_RUNTIME_DIR
-  ZDOTDIR
+    CODESPACES
+    COLORTERM
+    DBUS_SESSION_BUS_ADDRESS
+    NODENV_ROOT
+    PATH
+    PYENV_ROOT
+    RBENV_ROOT
+    SSH_TTY
+    SUDO_USER
+    TMPDIR
+    TMUX
+    XDG_CACHE_HOME
+    XDG_DATA_DIRS
+    XDG_RUNTIME_DIR
+    ZDOTDIR
 )
 for VAR in "${USED_BY_HOMEBREW_VARS[@]}"
 do
-  # Skip if variable value is empty.
-  [[ -z "${!VAR:-}" ]] && continue
-
-  # We unconditionally override `HOMEBREW_*` here.
-  VAR_NEW="HOMEBREW_${VAR}"
-  export "${VAR_NEW}"="${!VAR}"
+    # Skip if variable value is empty.
+    [[ -z "${!VAR:-}" ]] && continue
+    
+    # We unconditionally override `HOMEBREW_*` here.
+    VAR_NEW="HOMEBREW_${VAR}"
+    export "${VAR_NEW}"="${!VAR}"
 done
 
 unset VAR VAR_NEW MANPAGE_VARS USED_BY_HOMEBREW_VARS
@@ -223,7 +225,7 @@ export HOMEBREW_USER_CONFIG_HOME
 # Use VISUAL if HOMEBREW_EDITOR and EDITOR are unset.
 if [[ -z "${HOMEBREW_EDITOR:-}" && -n "${VISUAL:-}" ]]
 then
-  export HOMEBREW_EDITOR="${VISUAL}"
+    export HOMEBREW_EDITOR="${VISUAL}"
 fi
 
 # set from user environment
@@ -232,12 +234,12 @@ fi
 # (Set by default on GitHub Actions, Circle and Travis CI)
 if [[ -z "${CI:-}" ]] && [[ -n "${TF_BUILD:-}" || -n "${JENKINS_HOME:-}" ]]
 then
-  export CI="1"
+    export CI="1"
 fi
 
 if [[ -n "${GITHUB_ACTIONS:-}" && -n "${ImageOS:-}" && -n "${ImageVersion:-}" ]]
 then
-  export HOMEBREW_GITHUB_HOSTED_RUNNER=1
+    export HOMEBREW_GITHUB_HOSTED_RUNNER=1
 fi
 
 # filter the user environment
@@ -245,40 +247,40 @@ PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 
 FILTERED_ENV=()
 ENV_VAR_NAMES=(
-  HOME SHELL PATH TERM TERMINFO TERMINFO_DIRS COLUMNS DISPLAY LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS
-  http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY
+    HOME SHELL PATH TERM TERMINFO TERMINFO_DIRS COLUMNS DISPLAY LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS
+    http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY
 )
 # Filter all but the specific variables.
 for VAR in "${ENV_VAR_NAMES[@]}" "${!HOMEBREW_@}"
 do
-  # Skip if variable value is empty.
-  [[ -z "${!VAR:-}" ]] && continue
-
-  FILTERED_ENV+=("${VAR}=${!VAR}")
+    # Skip if variable value is empty.
+    [[ -z "${!VAR:-}" ]] && continue
+    
+    FILTERED_ENV+=("${VAR}=${!VAR}")
 done
 
 if [[ -n "${CI:-}" ]]
 then
-  for VAR in "${!GITHUB_@}"
-  do
-    # Skip if variable value is empty.
-    [[ -z "${!VAR:-}" ]] && continue
-    # Skip variables that look like tokens.
-    [[ "${VAR}" = *TOKEN* ]] && continue
-
-    FILTERED_ENV+=("${VAR}=${!VAR}")
-  done
+    for VAR in "${!GITHUB_@}"
+    do
+        # Skip if variable value is empty.
+        [[ -z "${!VAR:-}" ]] && continue
+        # Skip variables that look like tokens.
+        [[ "${VAR}" = *TOKEN* ]] && continue
+        
+        FILTERED_ENV+=("${VAR}=${!VAR}")
+    done
 fi
 
 if [[ -n "${HOMEBREW_RDBG:-}" ]]
 then
-  for VAR in "${!RUBY_DEBUG_@}"
-  do
-    # Skip if variable value is empty.
-    [[ -z "${!VAR:-}" ]] && continue
-
-    FILTERED_ENV+=("${VAR}=${!VAR}")
-  done
+    for VAR in "${!RUBY_DEBUG_@}"
+    do
+        # Skip if variable value is empty.
+        [[ -z "${!VAR:-}" ]] && continue
+        
+        FILTERED_ENV+=("${VAR}=${!VAR}")
+    done
 fi
 
 unset VAR ENV_VAR_NAMES
